services:
  db:
    image: iiycbka/sql-orm-benchmarks-db:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    networks:
      - root
    healthcheck:
      test: ["CMD", "/usr/local/bin/check_db.sh"]
      interval: 10s
      timeout: 5s
      retries: 60

  runner:
    build:
      context: ${RUNNER_BUILD_CONTEXT:-./benchmarks/sqlalchemy_bench}
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: ${RUNNER_COMMAND:-sync}
    networks:
      - root

volumes:
  postgres_data:

networks:
  root:
    driver: bridge